### ISSUE TITLE
HomeScreen_ Hiện màu chữ và ngôn ngữ cùng hiển thị đang có vấn đề xem ở hình ảnh dưới 

### ISSUE THREAD

**Issue by leeking29081994** [leeking29081994/bikerental#24]
![image](https://user-images.githubusercontent.com/95744803/145703849-ef67d4e4-dc75-4c0c-813e-ba28e4e88bae.png)
![image](https://user-images.githubusercontent.com/95744803/145703854-c1fc4884-4aa6-49b1-8b24-5c0b8c6443e4.png)
![image](https://user-images.githubusercontent.com/95744803/145703865-188444e3-0c06-4f29-92eb-56a7fac1df42.png)
![image](https://user-images.githubusercontent.com/95744803/145703869-77ccbbb8-df3a-413f-b4c6-4043572887d9.png)
![image](https://user-images.githubusercontent.com/95744803/145703905-b33cf65b-e657-4093-a151-088626099426.png)

**Comment by ninhnguyen1994** [comment]
Tôi đã fix issues tại pullrequest #27
