### ISSUE TITLE
Màn hình đăng nhập ,đăng ký, quên mật khẩu chuyển EN về VN và check kỹ màu chữ , chính tả

### ISSUE THREAD

**Issue by leeking29081994** [leeking29081994/bikerental#30]
![image](https://user-images.githubusercontent.com/95744803/145707011-ee08bf6a-2d8e-47c9-b3ee-e6ee61ff993a.png)
![image](https://user-images.githubusercontent.com/95744803/145707019-99e6c4ba-97c3-4e70-a05e-b63235d87f66.png)
![image](https://user-images.githubusercontent.com/95744803/145707036-a12e8bbf-5a82-4ad5-a4b6-2adbd0f84fa7.png)

**Comment by Uyenhoang205** [comment]
Em cam on thay a
