### ISSUE TITLE
Create Brand,Manage Brands_Screen chuyển EN->VN

### ISSUE THREAD

**Issue by leeking29081994** [leeking29081994/bikerental#32]
![image](https://user-images.githubusercontent.com/95744803/145707142-60940ee6-3b36-4a72-8767-2129f5084d17.png)
![image](https://user-images.githubusercontent.com/95744803/145707153-5fe187ed-5a37-419a-84d0-c1c4a272e146.png)

**Comment by Vutridang** [comment]
Cho em hỏi chút phần Show 10 entires và phần search ở file nào vậy em tìm trong các file manage-brand với các file đã include rồi nhưng không thấy hay phần này không cần dịch

**Comment by Vutridang** [comment]
đã fix bug xong
