### ISSUE TITLE
ChangeText_Chuyển đổi text của màn hình About us từ EN sang VN

### ISSUE THREAD

**Issue by leeking29081994** [leeking29081994/bikerental#5]
![image](https://user-images.githubusercontent.com/95744803/145331493-911ffe14-54cc-48a1-ae9f-9f25e14de54b.png)

**Comment by leeking29081994** [comment]
Dich phần trong ảnh 
![Uploading image.png…]()

**Comment by leeking29081994** [comment]
Dịch phần trong ảnh 
![image](https://user-images.githubusercontent.com/95744803/145704033-422e0bc2-78ae-44ec-972a-ba6cadbf6e88.png)

**Comment by Uyenhoang205** [comment]
em da fix fan nay tai pull request #42
